spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: test
    password: test
    driverClassName: com.mysql.cj.jdbc.Driver

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info