spring:
  application:
    name: demo-testcontainer
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: never
  profiles:
    default: local
  datasource:
     hikari:
       allow-pool-suspension: true